# Generated by Django 3.2.3 on 2021-08-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(height_field='height', upload_to='product/images', verbose_name='image', width_field='width')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
