# Generated by Django 3.2.3 on 2021-10-07 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dapi', '0005_auto_20211003_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature',
            field=models.CharField(default=None, max_length=555),
        ),
        migrations.AlterField(
            model_name='productfeatures',
            name='feature',
            field=models.TextField(blank=True, null=True, verbose_name='features'),
        ),
        migrations.AlterField(
            model_name='productfeatures',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='dapi.product'),
        ),
    ]
