# Generated by Django 3.2.3 on 2021-10-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapi', '0007_auto_20211007_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
