# Generated by Django 3.2.3 on 2021-10-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapi', '0008_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=150, null=True, unique=True),
        ),
    ]
